homepage_featured:
  - les_meves_ajudes
  - leximpact_socio_fiscal
showcase:
  author:
    types:
      icons:
        default: user
        individual: user
        collective: users
        ngo: globe
        research_center: graduation-cap
        business: factory
        local_institution: building
        state_institution: landmark
